# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails_dt}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Fortuna"]
  s.date = %q{2011-07-10}
  s.description = %q{Rails Debug Toolkit}
  s.email = %q{alex.r@askit.org}
  s.extra_rdoc_files = [
    "README.html",
    "README.md"
  ]
  s.files = [
    "README.html",
    "README.md",
    "VERSION.yml",
    "generators/rails_dt/USAGE",
    "generators/rails_dt/WARNING",
    "generators/rails_dt/rails_dt_generator.rb",
    "generators/rails_dt/templates/INSTALL",
    "generators/rails_dt/templates/dt.css",
    "generators/rails_dt/templates/dt.rb",
    "init.rb",
    "lib/dt.rb",
    "lib/dt/action_controller_extensions.rb",
    "lib/generators/rails_dt/USAGE",
    "lib/generators/rails_dt/rails_dt_generator.rb",
    "lib/generators/rails_dt/templates/INSTALL",
    "lib/generators/rails_dt/templates/dt.css",
    "lib/generators/rails_dt/templates/dt.rb",
    "lib/rails_dt.rb",
    "rails_dt.gemspec"
  ]
  s.homepage = %q{http://github.com/dadooda/rails_dt}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Rails Debug Toolkit}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

